Implement (de)serialization for Box, Arc, and Rc, and serialization for references
We can't implement deserialization for references because something has
to own them.

Unfortunately, we can't have a blanket impl for `Deref`:

```
error[E0119]: conflicting implementations of trait `traits::copy_type::CopyType` for type `[_; _]`
  --> epserde/src/impls/deref.rs:19:1
   |
19 | impl<T: Deref<Target: CopyType>> CopyType for T {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `[_; _]`
   |
  ::: epserde/src/impls/array.rs:19:1
   |
19 | impl<T: CopyType, const N: usize> CopyType for [T; N] {
   | ----------------------------------------------------- first implementation here
   |
   = note: upstream crates may add a new impl of trait `std::ops::Deref` for type `[_; _]` in future versions
```

and also not for `Borrow<_>`:

```
error[E0119]: conflicting implementations of trait `traits::copy_type::CopyType` for type `[_; _]`
  --> epserde/src/impls/deref.rs:19:1
   |
19 | impl<Borrowed: CopyType, T: Borrow<Borrowed>> CopyType for T {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `[_; _]`
   |
  ::: epserde/src/impls/array.rs:19:1
   |
19 | impl<T: CopyType, const N: usize> CopyType for [T; N] {
   | ----------------------------------------------------- first implementation here

error[E0207]: the type parameter `Borrowed` is not constrained by the impl trait, self type, or predicates
  --> epserde/src/impls/deref.rs:19:6
   |
19 | impl<Borrowed: CopyType, T: Borrow<Borrowed>> CopyType for T {
   |      ^^^^^^^^ unconstrained type parameter
```